using System;
using System.Collections.Generic;
using System.Text;

namespace Service.Contracts
{
	public interface IEventQueue:IDisposable
	{
		event Action<EQEventInfo> OnEventRegistered;

		string Subscribe<T>(Action<T> action)
			where T : EQEventInfo;

		void Unsubscribe<T>(string token)
			 where T : EQEventInfo;

		void Send<T>(T eventInfo)
			where T : EQEventInfo;

		void Send(object evt, EventSource source);

		void SendWithDelay<T>(int delay, T eventInfo)
			where T : EQEventInfo;

		void InvokeSubscribers<T>(T eventInfo)
			where T : EQEventInfo;
	}


	public abstract class EQEventInfo
	{
		public EventSource Source { get; internal set; }	// Indicates the source of this event. Possible values include Local (the event was generated by the local process), Remote (the event was generated on a remote process, i.e. it was received through a network connection).
		public string EventName { get; set; }       // The name of the event being generated (this is the name of the C# type name used to represent the event)
		public int CompanyID { get; set; }          // The company for which this event is being generated. When 0 it means the event is not related to a specific company, in such a case, the event should only be delivered if the user receiving the notification is an IDT user.
		public int RetryCount { get; set; }			// Counter with the number of times this event has been retried. Can be used to determine when to give up, trigger an alternate processing, or when to register an error notification that catches the attention of a user.
	}

	public enum EventSource
	{
		Local,
		Remote
	}
}
