using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;

namespace Service.Contracts
{
	public interface ITagEncodingAlgorithm
	{
		/// <summary>
		/// Sequence used to retrieve serial numbers
		/// </summary>
		ISerialSequence Sequence { get; }

		/// <summary>
		/// Gets a flag indicating if the algorithm has been configured to be serialized (each label is unique)
		/// </summary>
		bool IsSerialized { get; }

		/// <summary>
		/// Generates the RFID encoding information required to program a tag using the supplied product data. 
		/// </summary>
		/// <returns>Returns the information required to program an RFID tag</returns>
		/// <remarks>
		/// The variable data of the product is required because there are encoding algorithms that require information from the product. Also, the product data can be used to generate the TrackingBarcode.
		/// </remarks>
		List<TagEncodingInfo> Encode(EncodeRequest request);

        /// <summary>
        /// Generates the barcode required as Header for the "Mesa" encoding process
        /// </summary>
        string EncodeHeader(JObject data, int count, long startingSerial, int tagsPerSheet = 1);

		/// <summary>
		/// Generates the RFID encoding information required to program a tag using the supplied product data. This method does not consume serials from the configured sequence.
		/// </summary>
		/// <param name="data">Variable data of the product, must be a flat representation of the VariableData catalog and all related tables, this flat representation can be generated by calling DyncamicDB.FlattenObject</param>
		/// <returns>Returns the information required to program an RFID tag</returns>
		/// <remarks>
		/// EncodeSample WILL NOT consume serial numbers from the configured serial sequence, and therefore, there is no guaranty that the EPC returned is unique.
		/// </remarks>
		TagEncodingInfo EncodeSample(JObject data);
	}

	public class EncodeRequest
	{
		public int OrderID { get; set; }
		public int DetailID { get; set; }
		public string OrderNumber { get; set; } // Client order number
		public JObject VariableData { get; set; }
		public int Quantity { get; set; }
		public int TagsPerSheet { get; set; }

		public EncodeRequest() { }

		public EncodeRequest(int orderID, string orderNumber, int detailID, JObject data, int quantity, int tagsPerSheet)
		{
			OrderID = orderID;
			OrderNumber = orderNumber;
			DetailID = detailID;
			VariableData = data;
			Quantity = quantity;
			TagsPerSheet = tagsPerSheet;
		}
	}

	public interface ITagEncodingInfoUI
    {
        int UnitID { get; set; }
        string EPC { get; set; }
        string Barcode { get; set; }
        long SerialNumber { get; set; }
        bool WriteUserMemory { get; set; }
        string UserMemory { get; set; }
        bool WriteAccessPassword { get; set; }
        string AccessPassword { get; set; }
        bool WriteKillPassword { get; set; }
        string KillPassword { get; set; }
        bool WriteLocks { get; set; }
        RFIDLockType EPCLock { get; set; }
        RFIDLockType UserLock { get; set; }
        RFIDLockType AccessLock { get; set; }
        RFIDLockType KillLock { get; set; }
        string TrackingCode { get; set; }
        bool VerifyRFIDWhilePrinting { get; set; }
        int Product { get; set; }
        string Size { get; set; }
        string Color { get; set; }
        string TXT1 { get; set; }
        string TXT2 { get; set; }
        string TXT3 { get; set; }
        int InlayConfigID { get; set; } // LabelService exclude this field when is null
        string InlayConfigDescription { get; set; }
    }



    public class TagEncodingInfo 
	{
		public int UnitID { get; set; }
        public virtual string EPC { get; set; }
        public virtual string Barcode { get; set; }
        public long SerialNumber { get; set; }
		public bool WriteUserMemory { get; set; }
		public string UserMemory { get; set; }
		public bool WriteAccessPassword { get; set; }
		public string AccessPassword { get; set; }
		public bool WriteKillPassword { get; set; }
		public string KillPassword { get; set; }
		public bool WriteLocks { get; set; }
		public RFIDLockType EPCLock { get; set; }
		public RFIDLockType UserLock { get; set; }
		public RFIDLockType AccessLock { get; set; }
		public RFIDLockType KillLock { get; set; }
		public string TrackingCode { get; set; }
		public bool VerifyRFIDWhilePrinting { get; set; }
    }

    public class TagEncodingInfoUI :  TagEncodingInfo , ITagEncodingInfoUI
    {       
        public int Product { get; set; }
        [MaxLen(64)]
        public string Size { get; set; }
        [MaxLen(64)]
        public string Color { get; set; }
        [MaxLen(240)]
        public string TXT1 { get; set; }
        [MaxLen(240)]
        public string TXT2 { get; set; }
        [MaxLen(240)]
        public string TXT3 { get; set; }
        [IgnoreField]
        public int InlayConfigID { get; set; } // LabelService exclude this field when is null
        [MaxLen(32)]
        public string InlayConfigDescription { get; set; }
        [MaxLen(64)]
        public override string EPC { get; set; }
        [MaxLen(64)]
        public override string Barcode { get; set; }

        public TagEncodingInfoUI()
        {
        }

        public TagEncodingInfoUI(TagEncodingInfo tagEncodingInfo)
        {
            this.UnitID = tagEncodingInfo.UnitID;
            this.EPC = tagEncodingInfo.EPC;
            this.Barcode = tagEncodingInfo.Barcode;
            this.SerialNumber = tagEncodingInfo.SerialNumber;
            this.WriteUserMemory = tagEncodingInfo.WriteUserMemory;
            this.UserMemory = tagEncodingInfo.UserMemory;
            this.WriteAccessPassword = tagEncodingInfo.WriteAccessPassword;
            this.AccessLock = tagEncodingInfo.AccessLock;
            this.AccessPassword = tagEncodingInfo.AccessPassword;
            this.WriteKillPassword = tagEncodingInfo.WriteKillPassword;
            this.KillPassword = tagEncodingInfo.KillPassword;
            this.WriteLocks = tagEncodingInfo.WriteLocks;
            this.EPCLock = tagEncodingInfo.EPCLock;
            this.UserLock = tagEncodingInfo.UserLock;
            this.AccessLock = tagEncodingInfo.AccessLock;
            this.KillLock = tagEncodingInfo.KillLock;
            this.TrackingCode = tagEncodingInfo.TrackingCode;
            this.VerifyRFIDWhilePrinting = tagEncodingInfo.VerifyRFIDWhilePrinting;
        }
    }


    public enum RFIDLockType
	{
		UnLock = 0,
		Lock = 1,
		PermaLock = 2,
		PermaUnlock = 3,
		Mask = 4
	}

	public enum RFIDLockOverride
	{
		DoNotOverride = -2,
		MatchAccessLock = -1,
		UnLock = 0,
		Lock = 1,
		PermaLock = 2,
		PermaUnlock = 3,
		Mask = 4
	}
}
