using Service.Contracts;
using Service.Contracts.PrintCentral;
using Services.Core;
using System;
using System.Transactions;
using WebLink.Contracts;
using WebLink.Contracts.Models;

namespace WebLink.Services.Automated
{
    public class OrderExistVerifier : EQEventHandler<StartOrderProcessingEvent>
    {
        private IOrderUpdateService orderUpdateService;
        private IProjectRepository projectRepo;
        private IOrderRepository orderRepo;
        private IPluginManager<IOrderProcessingPlugin> pluginManager;
        private IEventQueue events;
        private ILogService log;
    
        public OrderExistVerifier(
            IOrderUpdateService orderUpdateService,
            IOrderRepository orderRepo,
            IProjectRepository projectRepo,
            IPluginManager<IOrderProcessingPlugin> pluginManager,
            IEventQueue events,
            ILogService log
        )
        {
            this.orderUpdateService = orderUpdateService;
            this.projectRepo = projectRepo;
            this.pluginManager = pluginManager;
            this.orderRepo = orderRepo;
            this.events = events;
            this.log = log;
        }

        public override EQEventHandlerResult HandleEvent(StartOrderProcessingEvent e)
        {
            // if order has order workflow dont't process the event
            var order = orderRepo.GetByID(e.OrderID);
            if (order.HasOrderWorkflow)
                return EQEventHandlerResult.OK;

            var response = orderUpdateService.Execute(
                e.OrderGroupID, e.OrderID,
                e.OrderNumber, e.ProjectID, e.BrandID);

            var result = new EQEventHandlerResult() { Success = false };

            switch (response)
            {
                case 0: // New Order
                case 1: // Auto Updated
                    result.Success = true;
                    events.Send(new OrderExistVerifiedEvent(e));
                    //log.LogMessage($"Order (ID:{e.OrderID}) has been accepted.");
                    break;
                case 2:
                    result.Success = true;
                    events.Send(new OrderDocumentsCompletedEvent(e)); // by pass for ProductionLocation.CustomerLocation
                    break;
                case 3: // cancel event
                case 4: // order generated by validation process
                    result.Success = true;
                    break;
                case -2: // Rejected - Disabled Updates
                case -3: // Rejected - Is the same order
                    result.Success = true;
                    break;

                case -4: // conflict detected
                    events.Send(new OrderConflictEvent(e));
                    result.Success = true; // cancel event, triggered after conflict resolution
                    break;

                case -1: // Wait
                default: // Unknown
                    result.Success = false;
                    break;
            }

            if (result.Success)
            {
                ParseCompo(order);
            }

            return result;
        }

        private void ParseCompo(IOrder order)
        {
            var project = projectRepo.GetByID(order.ProjectID);
            if (project != null && !String.IsNullOrWhiteSpace(project.OrderPlugin) && project.OrderWorkflowConfigID == null)
            {

                var orderData = new OrderPluginData()
                {
                    CompanyID = order.CompanyID,
                    BrandID = project.BrandID,
                    ProjectID = order.ProjectID,
                    OrderID = order.ID,
                    OrderGroupID = order.OrderGroupID,
                    OrderNumber = order.OrderNumber
                };

                try
                {
                    using(var suppressedScope = new TransactionScope(TransactionScopeOption.Suppress))
                    {
                        using(var plugin = pluginManager.GetInstanceByName(project.OrderPlugin))
                        {
                            plugin.OrderReceived(orderData);
                        }
                    }
                }
                catch (Exception ex)
                {
                    // ???: Register notification
                    log.LogException($"OrderFileReceivedEvent: Error while executing order plugin {project.OrderPlugin} for order {order.ID}.", ex);
                }
            }
        }
    }
}
