using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Service.Contracts;
using Service.Contracts.LabelService;
using Services.Core;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebLink.Contracts.Models;

namespace WebLink.Controllers
{
	[AllowAnonymous]
	public class LabelServiceController : Controller
    {
		private IAppConfig config;
		private ILogService log;
		private IFactory factory;
		private IRemoteFileStore store;

		public LabelServiceController(
			IAppConfig config,
			ILogService log,
			IFileStoreManager storeManager,
			IFactory factory)
		{
			this.config = config;
			this.log = log;
			this.factory = factory;
			store = storeManager.OpenStore("ProjectStore");
		}

		[HttpPost, Route("/labels/printarticle")]
		public async Task<LabelServiceResponse> PrintArticle([FromBody]PrintToFileRequest rq)
		{
			try
			{
				// Fix the resource path
				// The one generated by the print local points to a directory in the remote server, we have to change it to point to the local server.
				var repo = factory.GetInstance<ILabelRepository>();
				var gs = rq.ExportedData.FirstOrDefault(c => c.Name == "GlobalSettings");
				var array = JArray.Parse(gs.Records);

                var label = repo.GetByID(rq.LabelID);
                if (label != null)
                    rq.ProjectID = label.ProjectID != null ? label.ProjectID.Value : 1;

				(array[0] as JObject)["ResourcePath"] = repo.GetResourceDirectory(rq.ProjectID);
				gs.Records = array.ToString();

				var labelFile = await store.GetFileAttachmentAsync(rq.ProjectID, "Labels", label.FileName);
				rq.LabelFileGUID = labelFile.FileGUID;

				// Create the PRN file
				var client = factory.GetInstance<IBLabelServiceClient>();
				client.Url = config.GetValue<string>("WebLink.LabelService");
				var result = await client.PrintArticleAsync(rq);
				return result;
			}
			catch (Exception ex)
			{
				log.LogException(ex);
				return new LabelServiceResponse() { Success = false, ErrorMessage = ex.Message };
			}
		}

        [HttpPost, Route("/labels/pdflabelfilecontent")]
        public async Task<LabelServiceResponse> PDFLabelFileContent([FromBody]PrintPDFRequest rq)
        {
            try
            {
                // Fix the resource path
                // The one generated by the print local points to a directory in the remote server, we have to change it to point to the local server.
                var repo = factory.GetInstance<ILabelRepository>();
                var gs = rq.ExportedData.FirstOrDefault(c => c.Name == "GlobalSettings");
                var array = JArray.Parse(gs.Records);

                var label = repo.GetByID(rq.LabelID);
                if (label != null)
                    rq.ProjectID = label.ProjectID != null ? label.ProjectID.Value : 1;

                (array[0] as JObject)["ResourcePath"] = repo.GetResourceDirectory(rq.ProjectID);
                gs.Records = array.ToString();

                var labelFile = await store.GetFileAttachmentAsync(rq.ProjectID, "Labels", label.FileName);
                rq.LabelFileGUID = labelFile.FileGUID;

                // Create the PRN file
                var client = factory.GetInstance<IBLabelServiceClient>();
                client.Url = config.GetValue<string>("WebLink.LabelService");
                var result = await client.PrintPDFLibAsync(rq);
                return result;
            }
            catch (Exception ex)
            {
                log.LogException(ex);
                return new LabelServiceResponse() { Success = false, ErrorMessage = ex.Message };
            }
        }
    }
}