// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebLink.Contracts.Models;

namespace WebLink.Contracts.Migrations
{
    [DbContext(typeof(PrintDB))]
    [Migration("20200128133746_PrintPackageRev2")]
    partial class PrintPackageRev2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebLink.Contracts.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(40);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(40);

                    b.Property<string>("CityOrTown")
                        .HasMaxLength(25);

                    b.Property<string>("Country")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Default");

                    b.Property<string>("Name")
                        .HasMaxLength(40);

                    b.Property<string>("Notes");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(8);

                    b.HasKey("ID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleCode")
                        .HasMaxLength(25);

                    b.Property<string>("BillingCode")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Instructions");

                    b.Property<int?>("LabelID");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<int?>("ProjectID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("LabelID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Artifact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArticleID");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("LabelID");

                    b.Property<int>("LayerLevel");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<int>("Position");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("LabelID");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("EnableFTPFolder");

                    b.Property<string>("FTPFolder");

                    b.Property<byte[]>("Icon");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("RFIDConfigID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RFIDConfigID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Catalog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Captions");

                    b.Property<int>("CatalogID");

                    b.Property<int>("CatalogType");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Definition");

                    b.Property<bool>("IsHidden");

                    b.Property<bool>("IsReadonly");

                    b.Property<bool>("IsSystem");

                    b.Property<string>("Name");

                    b.Property<int>("ProjectID");

                    b.Property<string>("RequiredRoles");

                    b.Property<int>("SortOrder");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientContact1");

                    b.Property<string>("ClientContact2");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Culture")
                        .HasMaxLength(10);

                    b.Property<string>("CustomerSupport1");

                    b.Property<string>("CustomerSupport2");

                    b.Property<int?>("DefaultProductionLocation");

                    b.Property<string>("FtpPassword")
                        .HasMaxLength(500);

                    b.Property<string>("FtpUser")
                        .HasMaxLength(20);

                    b.Property<string>("GSTCode")
                        .HasMaxLength(6);

                    b.Property<int?>("GSTID");

                    b.Property<string>("HeaderFields")
                        .HasMaxLength(200);

                    b.Property<string>("IDTZone")
                        .HasMaxLength(30);

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000);

                    b.Property<byte[]>("Logo");

                    b.Property<string>("MainContact")
                        .HasMaxLength(50);

                    b.Property<string>("MainContactEmail")
                        .HasMaxLength(50);

                    b.Property<int?>("MainLocationID");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("OrderSort")
                        .HasMaxLength(2000);

                    b.Property<string>("ProductionManager1");

                    b.Property<string>("ProductionManager2");

                    b.Property<int?>("RFIDConfigID");

                    b.Property<int?>("SLADays");

                    b.Property<bool>("ShowAsCompany");

                    b.Property<string>("StopFields")
                        .HasMaxLength(200);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("RFIDConfigID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.CompanyAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressID");

                    b.Property<int>("CompanyID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyAddresses");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.CompanyProvider", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DefaultProductionLocation");

                    b.Property<string>("Instructions");

                    b.Property<int>("ProviderCompanyID");

                    b.Property<int?>("SLADays");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyProviders");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<int>("CompanyID");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.DataImportColMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("CanBeEmpty");

                    b.Property<int>("ColOrder");

                    b.Property<int?>("DataImportMappingID");

                    b.Property<string>("DateFormat");

                    b.Property<int?>("DecimalPlaces");

                    b.Property<string>("FixedValue");

                    b.Property<int?>("Function");

                    b.Property<string>("FunctionArguments");

                    b.Property<bool?>("Ignore");

                    b.Property<string>("InputColumn");

                    b.Property<bool?>("IsFixedValue");

                    b.Property<DateTime?>("MaxDate");

                    b.Property<int?>("MaxLength");

                    b.Property<long?>("MaxValue");

                    b.Property<DateTime?>("MinDate");

                    b.Property<int?>("MinLength");

                    b.Property<long?>("MinValue");

                    b.Property<string>("TargetColumn");

                    b.Property<int?>("Type");

                    b.HasKey("ID");

                    b.HasIndex("DataImportMappingID");

                    b.ToTable("DataImportColMapping");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.DataImportMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColumnDelimiter")
                        .HasMaxLength(1);

                    b.Property<string>("Encoding")
                        .HasMaxLength(20);

                    b.Property<string>("FileNameMask")
                        .HasMaxLength(50);

                    b.Property<bool>("IncludeHeader");

                    b.Property<string>("LineDelimiter")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("ProjectID");

                    b.Property<string>("QuotationChar")
                        .HasMaxLength(1);

                    b.Property<int>("RootCatalog");

                    b.Property<string>("SourceCulture")
                        .HasMaxLength(10);

                    b.Property<string>("SourceType")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("DataImportMappings");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.EncodedLabel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessPassword")
                        .HasMaxLength(8);

                    b.Property<string>("ArticleCode")
                        .HasMaxLength(25);

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EPC")
                        .HasMaxLength(32);

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200);

                    b.Property<string>("KillPassword")
                        .HasMaxLength(8);

                    b.Property<int>("PrinterID");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(25);

                    b.Property<int>("ProductionLocationID");

                    b.Property<int>("ProductionType");

                    b.Property<int>("ProjectID");

                    b.Property<long>("Serial");

                    b.Property<bool>("Success");

                    b.Property<string>("TID")
                        .HasMaxLength(32);

                    b.HasKey("ID");

                    b.ToTable("EncodedLabels");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.GroupFileColumn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Key");

                    b.Property<int>("ProjectId");

                    b.Property<string>("TableName");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("ProjectId");

                    b.ToTable("GroupFileColumns");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.HerculesJobIdRange", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Current");

                    b.Property<int>("Max");

                    b.HasKey("ID");

                    b.ToTable("HerculesJobIdRange");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.LabelData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("DoubleSide");

                    b.Property<bool>("EncodeRFID");

                    b.Property<string>("Mappings");

                    b.Property<int?>("MaterialID");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("PreviewData");

                    b.Property<int?>("ProjectID");

                    b.Property<int>("Type");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(50);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(50);

                    b.Property<string>("CityOrTown")
                        .HasMaxLength(50);

                    b.Property<int>("CompanyID");

                    b.Property<string>("Country")
                        .HasMaxLength(30);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeliverTo")
                        .HasMaxLength(50);

                    b.Property<string>("FactoryCode")
                        .HasMaxLength(25);

                    b.Property<string>("Holidays");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("ProductionManager1");

                    b.Property<int?>("ProductionManager2");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int>("WorkingDays");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(8);

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Properties");

                    b.Property<bool>("ShowAsMaterial");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action");

                    b.Property<bool>("AutoDismiss");

                    b.Property<int>("CompanyID");

                    b.Property<int>("Count");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Data");

                    b.Property<string>("IntendedRole")
                        .HasMaxLength(30);

                    b.Property<string>("IntendedUser")
                        .HasMaxLength(30);

                    b.Property<string>("Message");

                    b.Property<string>("NKey")
                        .HasMaxLength(120);

                    b.Property<string>("Source")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssignedPrinterID");

                    b.Property<string>("BillTo")
                        .HasMaxLength(30);

                    b.Property<int>("BillToCompanyID");

                    b.Property<int>("CompanyID");

                    b.Property<bool>("ConfirmedByMD");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("LocationID");

                    b.Property<int>("OrderDataID");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(16);

                    b.Property<int>("OrderStatus");

                    b.Property<bool>("PreviewGenerated");

                    b.Property<bool?>("PrintPackageGenerated");

                    b.Property<int>("ProductionType");

                    b.Property<int>("ProjectID");

                    b.Property<int>("Quantity");

                    b.Property<string>("SendTo")
                        .HasMaxLength(30);

                    b.Property<int>("SendToCompanyID");

                    b.Property<int?>("SendToLocationID");

                    b.Property<int>("Source");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ProjectID");

                    b.ToTable("CompanyOrders");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Pack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<string>("PackCode")
                        .HasMaxLength(25);

                    b.Property<int>("ProjectID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PackArticle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("PackID");

                    b.Property<int>("Quantity");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("PackID");

                    b.ToTable("PackArticles");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Printer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeviceID")
                        .HasMaxLength(20);

                    b.Property<string>("DriverName")
                        .HasMaxLength(50);

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(30);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<bool>("IsRemote");

                    b.Property<DateTime?>("LastSeenOnline");

                    b.Property<int>("LocationID");

                    b.Property<string>("Name")
                        .HasMaxLength(35);

                    b.Property<string>("Port")
                        .HasMaxLength(50);

                    b.Property<string>("PrinterType")
                        .HasMaxLength(50);

                    b.Property<string>("ProductName")
                        .HasMaxLength(50);

                    b.Property<bool>("SupportsCutter");

                    b.Property<bool>("SupportsRFID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PrinterJob", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleID");

                    b.Property<int?>("AssignedPrinter");

                    b.Property<bool>("AutoStart");

                    b.Property<int>("CompanyID");

                    b.Property<int>("CompanyOrderID");

                    b.Property<DateTime?>("CompletedDate");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime?>("DueDate");

                    b.Property<int>("Encoded");

                    b.Property<int>("Errors");

                    b.Property<int>("Extras");

                    b.Property<bool>("PrintPackageGenerated");

                    b.Property<int>("Printed");

                    b.Property<int?>("ProductionLocationID");

                    b.Property<int>("ProjectID");

                    b.Property<int>("Quantity");

                    b.Property<bool>("SendToHercules");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("CompanyOrderID");

                    b.ToTable("PrinterJobs");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PrinterJobDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Encoded");

                    b.Property<int>("Errors");

                    b.Property<int>("Extras");

                    b.Property<int>("Printed");

                    b.Property<int>("PrinterJobID");

                    b.Property<int>("ProductDataID");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("PrinterJobID");

                    b.ToTable("PrinterJobDetails");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PrinterSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleID");

                    b.Property<bool>("ChangeOrientation");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CutBehavior");

                    b.Property<int>("Darkness");

                    b.Property<bool>("EnableCut");

                    b.Property<bool>("PauseOnError");

                    b.Property<int>("PrinterID");

                    b.Property<bool>("ResumeAfterCut");

                    b.Property<bool>("Rotated");

                    b.Property<int>("Speed");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<double>("XOffset");

                    b.Property<double>("YOffset");

                    b.HasKey("ID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("PrinterID");

                    b.ToTable("PrinterSettings");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllowExtrasDuringValidation");

                    b.Property<bool>("AllowOrderChangesAfterValidation");

                    b.Property<int>("AllowQuantityEdition");

                    b.Property<bool>("AllowVariableDataEdition");

                    b.Property<bool>("AlwaysRequireCompositionValidation");

                    b.Property<int>("BrandID");

                    b.Property<string>("ClientContact1");

                    b.Property<string>("ClientContact2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CustomerSupport1");

                    b.Property<string>("CustomerSupport2");

                    b.Property<int?>("DefaultFactory");

                    b.Property<string>("Description")
                        .HasMaxLength(4000);

                    b.Property<bool>("EnableAuthorizationWorkflow");

                    b.Property<bool>("EnableFTPFolder");

                    b.Property<bool>("EnableMultipleFiles");

                    b.Property<bool>("EnableValidationWorkflow");

                    b.Property<string>("FTPClients");

                    b.Property<string>("FTPFolder");

                    b.Property<bool>("Hidden");

                    b.Property<int?>("MaxExtras");

                    b.Property<int?>("MaxExtrasPercentage");

                    b.Property<int?>("MaxQuantity");

                    b.Property<int?>("MaxQuantityPercentage");

                    b.Property<string>("Name")
                        .HasMaxLength(35);

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(20);

                    b.Property<int?>("RFIDConfigID");

                    b.Property<int?>("SLADays");

                    b.Property<int>("UpdateType");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("RFIDConfigID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.ProjectImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Extension");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectID");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.RFIDConfig", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("SerializedConfig");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.ToTable("RFIDParameters");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.SerialSequence", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(40);

                    b.Property<string>("Filter")
                        .HasMaxLength(100);

                    b.Property<long>("NextValue");

                    b.HasKey("ID", "Filter");

                    b.ToTable("SerialSequences");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Article", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.LabelData", "Label")
                        .WithMany()
                        .HasForeignKey("LabelID");

                    b.HasOne("WebLink.Contracts.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Artifact", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID");

                    b.HasOne("WebLink.Contracts.Models.LabelData", "Label")
                        .WithMany()
                        .HasForeignKey("LabelID");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Brand", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebLink.Contracts.Models.RFIDConfig", "RFIDConfig")
                        .WithMany()
                        .HasForeignKey("RFIDConfigID");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Catalog", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Company", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.RFIDConfig", "RFIDConfig")
                        .WithMany()
                        .HasForeignKey("RFIDConfigID");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.CompanyAddress", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebLink.Contracts.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.CompanyProvider", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Contact", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.DataImportColMapping", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.DataImportMapping")
                        .WithMany("Mappings")
                        .HasForeignKey("DataImportMappingID");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.DataImportMapping", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.GroupFileColumn", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.LabelData", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID");

                    b.HasOne("WebLink.Contracts.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Location", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Notification", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Order", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebLink.Contracts.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("WebLink.Contracts.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Pack", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PackArticle", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebLink.Contracts.Models.Pack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Printer", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PrinterJob", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Order", "CompanyOrder")
                        .WithMany()
                        .HasForeignKey("CompanyOrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PrinterJobDetail", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.PrinterJob", "PrinterJob")
                        .WithMany()
                        .HasForeignKey("PrinterJobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.PrinterSettings", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebLink.Contracts.Models.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebLink.Contracts.Models.Project", b =>
                {
                    b.HasOne("WebLink.Contracts.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebLink.Contracts.Models.RFIDConfig", "RFIDConfig")
                        .WithMany()
                        .HasForeignKey("RFIDConfigID");
                });
#pragma warning restore 612, 618
        }
    }
}
