using Microsoft.EntityFrameworkCore.Migrations;

namespace WebLink.Contracts.Migrations
{
    public partial class CountryData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Afghanistan','AF','AFG','004');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Åland Islands','AX','ALA','248');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Albania','AL','ALB','008');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Algeria','DZ','DZA','012');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('American Samoa','AS','ASM','016');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Andorra','AD','AND','020');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Angola','AO','AGO','024');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Anguilla','AI','AIA','660');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Antarctica','AQ','ATA','010');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Antigua and Barbuda','AG','ATG','028');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Argentina','AR','ARG','032');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Armenia','AM','ARM','051');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Aruba','AW','ABW','533');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Australia','AU','AUS','036');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Austria','AT','AUT','040');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Azerbaijan','AZ','AZE','031');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bahamas','BS','BHS','044');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bahrain','BH','BHR','048');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bangladesh','BD','BGD','050');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Barbados','BB','BRB','052');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Belarus','BY','BLR','112');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Belgium','BE','BEL','056');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Belize','BZ','BLZ','084');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Benin','BJ','BEN','204');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bermuda','BM','BMU','060');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bhutan','BT','BTN','064');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bolivia (Plurinational State of)','BO','BOL','068');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bonaire, Sint Eustatius and Saba','BQ','BES','535');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bosnia and Herzegovina','BA','BIH','070');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Botswana','BW','BWA','072');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bouvet Island','BV','BVT','074');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Brazil','BR','BRA','076');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('British Indian Ocean Territory','IO','IOT','086');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Brunei Darussalam','BN','BRN','096');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Bulgaria','BG','BGR','100');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Burkina Faso','BF','BFA','854');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Burundi','BI','BDI','108');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cabo Verde','CV','CPV','132');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cambodia','KH','KHM','116');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cameroon','CM','CMR','120');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Canada','CA','CAN','124');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cayman Islands','KY','CYM','136');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Central African Republic','CF','CAF','140');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Chad','TD','TCD','148');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Chile','CL','CHL','152');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('China','CN','CHN','156');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Christmas Island','CX','CXR','162');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cocos (Keeling) Islands','CC','CCK','166');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Colombia','CO','COL','170');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Comoros','KM','COM','174');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Congo','CG','COG','178');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Congo, Democratic Republic of the','CD','COD','180');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cook Islands','CK','COK','184');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Costa Rica','CR','CRI','188');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Côte d''Ivoire','CI','CIV','384');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Croatia','HR','HRV','191');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cuba','CU','CUB','192');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Curaçao','CW','CUW','531');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Cyprus','CY','CYP','196');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Czechia','CZ','CZE','203');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Denmark','DK','DNK','208');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Djibouti','DJ','DJI','262');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Dominica','DM','DMA','212');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Dominican Republic','DO','DOM','214');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Ecuador','EC','ECU','218');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Egypt','EG','EGY','818');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('El Salvador','SV','SLV','222');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Equatorial Guinea','GQ','GNQ','226');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Eritrea','ER','ERI','232');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Estonia','EE','EST','233');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Eswatini','SZ','SWZ','748');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Ethiopia','ET','ETH','231');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Falkland Islands (Malvinas)','FK','FLK','238');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Faroe Islands','FO','FRO','234');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Fiji','FJ','FJI','242');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Finland','FI','FIN','246');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('France','FR','FRA','250');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('French Guiana','GF','GUF','254');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('French Polynesia','PF','PYF','258');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('French Southern Territories','TF','ATF','260');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Gabon','GA','GAB','266');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Gambia','GM','GMB','270');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Georgia','GE','GEO','268');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Germany','DE','DEU','276');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Ghana','GH','GHA','288');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Gibraltar','GI','GIB','292');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Greece','GR','GRC','300');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Greenland','GL','GRL','304');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Grenada','GD','GRD','308');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Guadeloupe','GP','GLP','312');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Guam','GU','GUM','316');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Guatemala','GT','GTM','320');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Guernsey','GG','GGY','831');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Guinea','GN','GIN','324');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Guinea-Bissau','GW','GNB','624');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Guyana','GY','GUY','328');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Haiti','HT','HTI','332');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Heard Island and McDonald Islands','HM','HMD','334');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Holy See','VA','VAT','336');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Honduras','HN','HND','340');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Hong Kong','HK','HKG','344');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Hungary','HU','HUN','348');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Iceland','IS','ISL','352');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('India','IN','IND','356');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Indonesia','ID','IDN','360');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Iran (Islamic Republic of)','IR','IRN','364');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Iraq','IQ','IRQ','368');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Ireland','IE','IRL','372');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Isle of Man','IM','IMN','833');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Israel','IL','ISR','376');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Italy','IT','ITA','380');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Jamaica','JM','JAM','388');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Japan','JP','JPN','392');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Jersey','JE','JEY','832');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Jordan','JO','JOR','400');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Kazakhstan','KZ','KAZ','398');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Kenya','KE','KEN','404');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Kiribati','KI','KIR','296');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Korea (Democratic People''s Republic of)','KP','PRK','408');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Korea, Republic of','KR','KOR','410');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Kuwait','KW','KWT','414');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Kyrgyzstan','KG','KGZ','417');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Lao People''s Democratic Republic','LA','LAO','418');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Latvia','LV','LVA','428');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Lebanon','LB','LBN','422');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Lesotho','LS','LSO','426');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Liberia','LR','LBR','430');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Libya','LY','LBY','434');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Liechtenstein','LI','LIE','438');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Lithuania','LT','LTU','440');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Luxembourg','LU','LUX','442');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Macao','MO','MAC','446');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Madagascar','MG','MDG','450');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Malawi','MW','MWI','454');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Malaysia','MY','MYS','458');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Maldives','MV','MDV','462');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Mali','ML','MLI','466');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Malta','MT','MLT','470');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Marshall Islands','MH','MHL','584');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Martinique','MQ','MTQ','474');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Mauritania','MR','MRT','478');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Mauritius','MU','MUS','480');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Mayotte','YT','MYT','175');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Mexico','MX','MEX','484');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Micronesia (Federated States of)','FM','FSM','583');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Moldova, Republic of','MD','MDA','498');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Monaco','MC','MCO','492');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Mongolia','MN','MNG','496');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Montenegro','ME','MNE','499');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Montserrat','MS','MSR','500');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Morocco','MA','MAR','504');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Mozambique','MZ','MOZ','508');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Myanmar','MM','MMR','104');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Namibia','NA','NAM','516');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Nauru','NR','NRU','520');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Nepal','NP','NPL','524');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Netherlands','NL','NLD','528');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('New Caledonia','NC','NCL','540');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('New Zealand','NZ','NZL','554');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Nicaragua','NI','NIC','558');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Niger','NE','NER','562');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Nigeria','NG','NGA','566');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Niue','NU','NIU','570');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Norfolk Island','NF','NFK','574');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('North Macedonia','MK','MKD','807');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Northern Mariana Islands','MP','MNP','580');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Norway','NO','NOR','578');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Oman','OM','OMN','512');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Pakistan','PK','PAK','586');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Palau','PW','PLW','585');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Palestine, State of','PS','PSE','275');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Panama','PA','PAN','591');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Papua New Guinea','PG','PNG','598');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Paraguay','PY','PRY','600');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Peru','PE','PER','604');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Philippines','PH','PHL','608');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Pitcairn','PN','PCN','612');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Poland','PL','POL','616');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Portugal','PT','PRT','620');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Puerto Rico','PR','PRI','630');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Qatar','QA','QAT','634');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Réunion','RE','REU','638');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Romania','RO','ROU','642');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Russian Federation','RU','RUS','643');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Rwanda','RW','RWA','646');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saint Barthélemy','BL','BLM','652');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saint Helena, Ascension and Tristan da Cunha','SH','SHN','654');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saint Kitts and Nevis','KN','KNA','659');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saint Lucia','LC','LCA','662');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saint Martin (French part)','MF','MAF','663');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saint Pierre and Miquelon','PM','SPM','666');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saint Vincent and the Grenadines','VC','VCT','670');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Samoa','WS','WSM','882');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('San Marino','SM','SMR','674');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Sao Tome and Principe','ST','STP','678');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Saudi Arabia','SA','SAU','682');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Senegal','SN','SEN','686');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Serbia','RS','SRB','688');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Seychelles','SC','SYC','690');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Sierra Leone','SL','SLE','694');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Singapore','SG','SGP','702');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Sint Maarten (Dutch part)','SX','SXM','534');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Slovakia','SK','SVK','703');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Slovenia','SI','SVN','705');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Solomon Islands','SB','SLB','090');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Somalia','SO','SOM','706');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('South Africa','ZA','ZAF','710');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('South Georgia and the South Sandwich Islands','GS','SGS','239');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('South Sudan','SS','SSD','728');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Spain','ES','ESP','724');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Sri Lanka','LK','LKA','144');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Sudan','SD','SDN','729');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Suriname','SR','SUR','740');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Svalbard and Jan Mayen','SJ','SJM','744');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Sweden','SE','SWE','752');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Switzerland','CH','CHE','756');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Syrian Arab Republic','SY','SYR','760');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Taiwan, Province of China','TW','TWN','158');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Tajikistan','TJ','TJK','762');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Tanzania, United Republic of','TZ','TZA','834');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Thailand','TH','THA','764');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Timor-Leste','TL','TLS','626');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Togo','TG','TGO','768');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Tokelau','TK','TKL','772');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Tonga','TO','TON','776');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Trinidad and Tobago','TT','TTO','780');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Tunisia','TN','TUN','788');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Turkey','TR','TUR','792');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Turkmenistan','TM','TKM','795');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Turks and Caicos Islands','TC','TCA','796');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Tuvalu','TV','TUV','798');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Uganda','UG','UGA','800');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Ukraine','UA','UKR','804');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('United Arab Emirates','AE','ARE','784');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('United Kingdom of Great Britain and Northern Ireland','GB','GBR','826');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('United States of America','US','USA','840');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('United States Minor Outlying Islands','UM','UMI','581');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Uruguay','UY','URY','858');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Uzbekistan','UZ','UZB','860');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Vanuatu','VU','VUT','548');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Venezuela (Bolivarian Republic of)','VE','VEN','862');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Viet Nam','VN','VNM','704');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Virgin Islands (British)','VG','VGB','092');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Virgin Islands (U.S.)','VI','VIR','850');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Wallis and Futuna','WF','WLF','876');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Western Sahara','EH','ESH','732');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Yemen','YE','YEM','887');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Zambia','ZM','ZMB','894');
                INSERT INTO Countries ([Name], [Alpha2], [Alpha3], [NumericCode]) VALUES ('Zimbabwe','ZW','ZWE','716');
                        ");

            // set old address to spain country
            migrationBuilder.Sql(@"update [dbo].[Addresses] SET CountryID = 210");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
