using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Service.Contracts
{
	public interface IAppLog
	{
		event EventHandler<ILogEntry> OnEventRegistered;
		event EventHandler OnTerninate;
		LogLevel LogLevel { get; set; }
		bool DebugLogging { get; set; }
		void InitializeLogFile(string baseFileName, int maxFileSize = 4194304);
		IAppLog GetSection(string name);
		void LogMessage(string message, params object[] args);
		void Trace(string message, params object[] args);
		void LogMessage(LogLevel targetLevel, string message, params object[] args);
		void LogWarning(string message, params object[] args);
		void LogWarning(string message, Exception ex);
		void LogException(Exception ex);
		void LogException(string message, Exception ex);
		void LogEvent(LogLevel targetLevel, string message, Exception exception, LogEntryType eventType);
		void LogEvent(ILogEntry e);
		void WaitForPendingNotifications();
		void Terminate();
	}

	// This refers to the app loader log level, notice that this setting is independent of IAppConfig.LogMessages...
	// IAppConfig.LogMessages only affects messages logged by the application through the base application class (for instance ServiceBase.LogMessage)
	// In the other hand, LogLevel affects the level of logging generated by the appliction host itself (the AppLoader)
	public enum LogLevel
	{
		Critical = 0,           // Logs errors and warnings only
		Default = 1,            // In addition to errors and warnings, this setting also logs messages (this is the default log level)
		Verbose = 2             // Logs all posible messages (Exceptions, Warnings, Messages and Trace messages). This setting is intended for debugging and troubleshooting and should rarely be used for stable services in a production environment, as it can cause the log file to grow rapidly and start recycling messages sooner.
	}

	/// <summary>
	/// Enumerates the different event types that can be generated in the Application
	/// </summary>
	public enum LogEntryType
	{
		/// <summary>
		/// Just an informative message, usually contains tracing information
		/// </summary>
		Message = 1,
		/// <summary>
		/// A message used to report an anormal situation that should be reviewed but does not stop the application from working.
		/// </summary>
		Warning = 2,
		/// <summary>
		/// A message used to report a serious error that might be preventing the system from working properly.
		/// </summary>
		Exception = 4
	}

	public interface ILogEntry
	{
		int PID { get; }
		int TID { get; }
		DateTime Date { get; }
		LogEntryType EntryType { get; }
		string Message { get; }
		string ExceptionType { get; }
		string StackTrace { get; }
		string ToString(bool useShortVersion);
	}


	public interface IAppLogFile : IDisposable
	{
		IAppLogFile Initialize(string fileName, int maxSize = 2097152);
		void LogEvent(ILogEntry e);
	}
}
